### ISSUE TITLE
Online server

### ISSUE THREAD

**Issue by paoloans** [aarcangeli/Serious-Sam-Android#16] opened 2019-05-16 21:31 UTC
I love this game but i want play the online there is possibility to play.

**Comment by aarcangeli** [comment] 2019-05-18 09:21
Multiplayer mode is not ported.
I was already thinking of implementing it.
The problem is that you probably won't be able to play between android and computer.

**Comment by K0CM0HABT** [comment] 2019-05-19 06:07
@aarcangeli some people play from the phone in cs1.6 and quake 3 on pc servers against pc players.:grinning:

If you do this in the future, it will be very cool, I would like to play in co-op mode

**Comment by aarcangeli** [comment] 2019-11-10 19:30
Conversation merged in #33

**Closed by aarcangeli** 2019-11-10 19:30 UTC
Labels: enhancement
